### ISSUE TITLE
Create osm service connection

### ISSUE THREAD

**Issue by mbrzakovic** [rapideditor/rapid-sdk#107]
Create osm service module.

Accent: Auth, Load(ents, tiles, user), Parse, putChangeset

Estimated effort (dev work days): 6d

Dependency: Osm entity model https://github.com/ideditor/id-sdk/issues/106

**Comment by bhousel** [comment]
Closing as stale, but we still do plan to do this.
All the service code in Rapid has been refreshed significantly and is a candidate to move over here.
