### ISSUE TITLE
Package naming convention

### ISSUE THREAD

**Issue by mbrzakovic** [rapideditor/rapid-sdk#115]
It is possible that the current package naming convention does not scale well.
Currently it includes only the name of most descendent folder. (e.g.: /math/extent -> @id-sdk/extent)
The problem can manifest in both package publishing and docs generation when we create services/osm which can overlap with osm module (both names would be: @id-sdk/osm).

Proposal:
Include path in module name via '-' delimiter (e.g. /math/extent -> @id-sdk/math-extent)

**Comment by bhousel** [comment]
This sounds ok to introduce an extra part to the name, would it look like this? 

```js
import { Extent } from '@id-sdk/math-extent';  // import just the extent
import { Extent } from '@id-sdk/math';  // this also works, as math re-exports its subpackages

import { Node, Way, Relation } from '@id-sdk/models-osm';
const n = new Node();

import { OSM } from '@id-sdk/services-osm';
```

It's also probably not too late to just do away with the subpackages completely?
We could just stick all the mathy stuff in `@id-sdk/math` and not even have subpackages?
```js
import { Extent } from '@id-sdk/math';
import { Node, Way, Relation } from '@id-sdk/models';
import { OSM } from '@id-sdk/services';
```

But I do like the idea of having this extra subpackage/namespace, because it would let us do stuff like this without too much breakage:
```js
// Future OSM has an Area data type
import { Node, Way, Area, Relation } from '@id-sdk/models-osm-future';

// Future OSM service supports fetching data from the protobuf endpoint
import { OSM as OSM2 } from '@id-sdk/services-osm-future';
```


@vanreece & @Bonkles  you had some thoughts on this too right?

**Comment by mbrzakovic** [comment]
> This sounds ok to introduce an extra part to the name, would it look like this?

Yes, correct.


> It's also probably not too late to just do away with the subpackages completely? We could just stick all the mathy stuff in `@id-sdk/math` and not even have subpackages?

I agree on this as well, I think that package containment for math module is perhaps too granular. In general it seems that the higher the granularity, the tougher the maintanence however the bigger the flexibility on cherry picking (a consumer could grab a more specific package which would reduce his overall bundle size).
In this case, file size is negligible and decreasing the number of math packages from 7 to 1 would reduce the maintanence effort notably.

**Comment by bhousel** [comment]
> I agree on this as well, I think that package containment for math module is perhaps too granular.

Cool - I'm going to do this today.. After using the sdk in practice for a few months I agree just `import { thing } from '@id-sdk/math'` feels easier.

**Comment by bhousel** [comment]
This was done! 
We've made the sdk a dependency for Rapid and have been using it for a while.

We usually do the imports like this:

```js
import { Extent, Projection, Tiler, geoZoomToScale, vecAdd } from '@rapid-sdk/math';
import { utilArrayChunk, utilArrayGroupBy, utilArrayUniq } from '@rapid-sdk/util';
```
